---
#- name: Ping Test
#  hosts: all
#  gather_facts: false
#  tasks:
#    - name: Ping the server
#      ansible.builtin.ping:


- name: Ping Windows Server
  hosts: all
  tasks:
    - name: Ping using win_ping
      ansible.windows.win_ping:

