---
   - name: Ping test with multiple ports
     hosts: all
     gather_facts: false
     vars:
       windows_ports: "{{ target_ports }}"
       
     tasks:
       - name: Check connectivity on each port
         ansible.builtin.wait_for:
           host: "{{ ansible_host }}"
           port: "{{ item.item }}"
           timeout: 5
           state: started
         loop: "{{ windows_ports }}"
         register: port_results
         ignore_errors: true  # Handle cases where some ports might not be open

       #- name: Gather results
        # debug:
         #  msg: "Port {{ item.item }}: {{ item.state }}"
         #loop: "{{ port_results.results }}"
         #when: item is defined

       - name: Display results
         ansible.builtin.debug:
           msg: "Host: {{ inventory_hostname }}, Port: {{ item }}, Status: {{ port_results.results[item_index].state }}"
         loop: "{{ windows_ports }}"
         loop_control:
           index_var: item_index

       #- name: Failed results
        # debug:
         #  msg: "Port {{ item.item }}: {{ item.msg }}"
         #loop: "{{ port_results.results }}"
         #when: item.msg is defined

