---
- name: Check port 443 on target host
  hosts: all  # Replace with your target host
  tasks:
    - name: Check if port 443 is open
      wait_for:
        host: all  # Replace with your target host
        port: 443
        timeout: 5  # Timeout in seconds
      delegate_to: localhost # Run this check from the tower server
      register: port_check_result

    - name: Debug the result
      debug:
        msg: "Port 443 is reachable on your_target_host"
      when: port_check_result.reachable
      
    - name: Debug the result
      debug:
        msg: "Port 443 is not reachable on your_target_host"
      when: not port_check_result.reachable

