---
- name: Test WinRM Port 5985
  hosts: all
  tasks:
    - name: Check if port 5985 is open on Windows server
      ansible.builtin.shell: "nc -zv {{ win_host }} 5985"
      register: result
      ignore_errors: yes

    - name: Show result
      ansible.builtin.debug:
        var: result.stdout

